name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version_number: ${{ steps.get_version_number.outputs.version_number }}

    environment:
      name: actions_back_front_orange_finance
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Get latest tag as build name
        id: get_version_number
        run: |
          git_tag=$(git describe --abbrev=0 --tags)
          git_tag_sub=${git_tag:1}
          echo "Build number: $git_tag_sub"
          echo "version_number=$git_tag_sub" >> $GITHUB_ENV
          echo "::set-output name=version_number::$git_tag_sub"


      - name: Echo the version number
        run: |
          echo "The version number is: ${{ env.version_number }}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore Back-Orange-Finance/Orange-Finance/OrangeFinance.csproj

      - name: Build application
        run: dotnet build Back-Orange-Finance/Orange-Finance/OrangeFinance.csproj --no-restore --configuration Release

      - name: Publish application
        run: dotnet publish Back-Orange-Finance/Orange-Finance/OrangeFinance.csproj --no-build --configuration Release -o out

  push-image:
      needs: build
      runs-on: ubuntu-latest
    
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            persist-credentials: false
        
        - name: Echo the version number
          run: |
               echo "The version number is: ${{ needs.build.outputs.version_number }}"
               echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}"
               echo ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Log in to DockerHub
          if: ${{ needs.build.outputs.version_number != '' }}
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push Docker image
          if: ${{ needs.build.outputs.version_number != '' }}
          uses: docker/build-push-action@v4
          with:
            context: Back-Orange-Finance
            file: Back-Orange-Finance/Orange-Finance/Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKER_USERNAME }}/orange-finance-backend:${{ needs.build.outputs.version_number }}
              ${{ secrets.DOCKER_USERNAME }}/orange-finance-backend:latest

        - name: Scan Docker image for vulnerabilities
          if: ${{ needs.build.outputs.version_number != '' }}
          uses: aquasecurity/trivy-action@0.29.0
          with:
            image-ref: ${{ secrets.DOCKER_USERNAME }}/orange-finance-backend:${{ needs.build.outputs.version_number }}
